# Build script for Travis CI
#

# use xenial distribution
dist: xenial

# no need to check for oracle's java
language: python
python: "3.7"

# speed up builds by caching pip, miniconda
cache:
  directories:
    - "$HOME/.cache/pip"

# only keep track of the master branch, for now
branches:
  only:
  - master

# added to make logs look cleaner, crisper, certified fresh
before_install: unset _JAVA_OPTIONS 

# see requirements.txt for details on dependencies
install:
  - pip install -r requirements.txt
  - pip install .

# this script will clone the passed repo and update its gh-pages branch with the lattest summary,
# make sure to include '[skip travis]' in the first commit message, otherwise we will end up in an endless loop!
# keeping complicated scripts separate is not much, but it's honest work
script: ./.generate-summary.py $TRAVIS_REPO_SLUG "[skip travis] Updated summary" "This commit was performed from travis-ci.com using a personal access key" "Build ID $TRAVIS_BUILD_ID" "Job ID TRAVIS_JOB_ID" "Branch $TRAVIS_BRANCH" "Log of this build found at $TRAVIS_JOB_WEB_URL"

# GitHub access credentials (username, acces token)
env:
  global:
    - secure: "dj9dZOTQ860pikVXn/IdPDY6qu5U5mprfFTvOIyfmvieA/RYionGkMnpjprEXXWshPZdYOs+bSf0c5r/OkryoG/gv6bGwS+j/wn8GSkfLI2XrF7JNEHJDgssY3Lyj/JbGXc4VoKJh93wWFwyBbamz9W684miI2Ln99rwiUXXe/Fm/V+xlMAnW2BBV2/acH45KZOsnhnvo7P7vbilXobUNRvuDoqcFaqWfTgkEtHZp02mpugsQxScioKGYyt+eQgVuM9wflvJvehkZDpYI+7ohu3ndTUUiRIfca4wiR15cLqD3X2/gVGTt/Oa3EKVVNfBkvMGTonrOxHXMAHkAb12BOfeEtWkTCFbPqygToZu7TW5qbfoUCssHTDRE7ArwnJdjMGWQCx0DDTJXD6UpHggJg3Gl5A0wRaXGKsZ+vBdchrOO2pm4irvGwYhi9U0cqQfHj7tB++UcIzn1Sb6cuizhT88yhLJ44uI3+m2pyobFth3j59d6QFpVB1Gf1I6qp7Nddt1iE584hat/v2632LoZh+93kFKP3JbAhkqQinJ7i3+Hg2eiMMNgDVduTsSeEZrazbAmnHz07eiTWLFQdSy+SQSVlKyVujgPYIpY26sDsdiDRoG7HHNurk/kkfHupg5hGvQr86HX5TZlmiMC6mHN6ZS6mQ9kHg9jvKiGzb9c7s="
    - secure: "4QC+WPZV+cI3IJ6aqX76dZF8gr+7+tvVH9w16c4SQf71bsExW0JsvQshjD12BTM8XRXxrta3GPKvwzv4PJm8Ubl9ZuGXQ5D9d8pB/KO75DHr51RtA8Y8Tr2iFmebHC3RhwGYYb6rAdgrrh30ItABcZYJT6hdXGZrWNoSUhpAua4u/JJa5N+JTSqjTs7qALQHVWR9X5wGwmtOEt0EjBFNnRNsVWxLXJd8HPb5iqcmt6i6g9z/i8icmK/+zRuzNXWyS6JmIDgyECnOhkn6/UePf3MxRaMtW69PU6jGUbEQ16aR4YJXNI4tt7xxIiCv7xB5iYSnJ6Zz0JAlBj9/pvut4LLNX/vt00Z87Ba5TnPGTPXsqpJZQESIhV9bslJ/Ye4cBCb4XXqyrjQpTbBWAJXrCMTdDLxQgclWAgO6ALzS58rJtFtyFJOoTyg1s4X/KrxxuZC46AURfghkkgeUeeLRnVXAlcMOX/Xm7Np1GHxSuPxkf945olPrh3xNulo5kiXKNLhP/FDtO96EYk8tNMRbTMH538t5agUKrqNIwfhmGsYfmYM3ZVp3O2Sxi08M3MMHkZOpLG/PVKIhHN9w0mDc2338GRzIZHy64YFFJYbHl297eiBRI1Ua0h/IuCxmXKS0LCLwyA9X2G4sfXFfUHpHNZdY/doPu761M+IG3C9BqvQ="
